# PROBLEM STATEMENT
### you are provided with a playstore data and asked to find out for a developer company which apps are widely used they want to create a new app to generate revenue by playing adds and getting views

## importing my custom module

In [1]:

import myfunc

In [2]:
import csv

## import dataset

In [3]:
import pandas as pd

In [4]:
data_df = pd.read_csv("playstore.csv")

In [6]:
## exploring dataset

In [5]:
data_df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [6]:
data_df["Category"]

0             ART_AND_DESIGN
1             ART_AND_DESIGN
2             ART_AND_DESIGN
3             ART_AND_DESIGN
4             ART_AND_DESIGN
                ...
10836                 FAMILY
10837                 FAMILY
10838                MEDICAL
10839    BOOKS_AND_REFERENCE
10840              LIFESTYLE
Name: Category, Length: 10841, dtype: object

## cleaning Install column to typecast

In [7]:
data_df["Installs"] = data_df["Installs"].str.replace(",","").str.strip("+")   # 1,00 = 100

In [8]:
data_df["Installs"].astype(int)

ValueError: invalid literal for int() with base 10: 'Free'

In [9]:
## checking why it raised error?
bol_ins =data_df["Installs"] == "Free"

In [10]:
data_df[bol_ins]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [11]:
## delete row that raised error
data_df = data_df.drop(10472)     #delete the row

In [12]:
data_df["Installs"] = data_df["Installs"].astype(int)

In [14]:
#checking data
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  object
 4   Size            10840 non-null  object
 5   Installs        10840 non-null  int32
 6   Type            10839 non-null  object
 7   Price           10840 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10840 non-null  object
 11  Current Ver     10832 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), int32(1), object(11)
memory usage: 1.1+ MB

# creating function to identify apps with engliash names

In [15]:
def eng_app(word_name):
    non_ascii = 0
    for i in word_name:
        word_ordi = ord(i)
        if word_ordi > 127:
            non_ascii += 1
    if non_ascii > 3:
        return False
    else:
        return True

In [16]:
#creating bool for english apps and saving it in variable
bol_eng_app = data_df["App"].apply(eng_app)
bol_eng_app.sum()       #only true values

10795

#standardizing our data

In [20]:
data_df.columns.str.upper()

Index(['APP', 'CATEGORY', 'RATING', 'REVIEWS', 'SIZE', 'INSTALLS', 'TYPE',
       'PRICE', 'CONTENT RATING', 'GENRES', 'LAST UPDATED', 'CURRENT VER',
       'ANDROID VER'],
      dtype='object')

In [21]:
data_df.loc[bol_eng_app , "App"]    # we can use bool series for indexing

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...
10836                                     Sya9a Maroc - FR
10837                     Fr. Mike Schmitz Audio Teachings
10838                               Parkinson Exercices FR
10839                        The SCP Foundation DB fr nn5n
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10795, dtype: object

In [23]:
len(bol_eng_app)     #it is considering all true and false values

10840

In [24]:
eng_app_df = data_df[bol_eng_app]     # extract all data with bool series indexing

In [25]:
eng_app_df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,5000,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,1000,Free,0,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [26]:
 # just to see my data
eng_app_df.iloc[555:560]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
555,Heart mill,DATING,3.3,4631,45M,100000,Free,0,Mature 17+,Dating,"August 4, 2018",5.2.14,5.0 and up
556,Once - Quality Matches Every day,DATING,4.4,222888,21M,1000000,Free,0,Mature 17+,Dating,"July 17, 2018",2.45,4.1 and up
557,Sudy – Meet Elite & Rich Single,DATING,4.1,17268,40M,500000,Free,0,Mature 17+,Dating,"June 25, 2018",4.1.2,4.0.3 and up
558,"muzmatch: Muslim & Arab Singles, Marriage & Da...",DATING,3.8,5164,25M,100000,Free,0,Mature 17+,Dating,"July 24, 2018",3.8.75a,4.0.3 and up
559,95Live -SG#1 Live Streaming App,DATING,4.1,4953,15M,1000000,Free,0,Teen,Dating,"August 1, 2018",8.7.2,4.2 and up

# extracting english apps which are free

In [28]:
bol_free_eng_app = eng_app_df["Type"] == "Free"

In [29]:
bol_free_eng_app.sum()

9998

In [30]:
free_eng_app_df =  eng_app_df[bol_free_eng_app]

In [31]:
#new data frame with english free apps data only
free_eng_app_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9998 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9998 non-null   object
 1   Category        9998 non-null   object
 2   Rating          8691 non-null   float64
 3   Reviews         9998 non-null   object
 4   Size            9998 non-null   object
 5   Installs        9998 non-null   int32
 6   Type            9998 non-null   object
 7   Price           9998 non-null   object
 8   Content Rating  9998 non-null   object
 9   Genres          9998 non-null   object
 10  Last Updated    9998 non-null   object
 11  Current Ver     9992 non-null   object
 12  Android Ver     9997 non-null   object
dtypes: float64(1), int32(1), object(11)
memory usage: 1.0+ MB

## for working on reviews we have to typecast it into integer

In [33]:
free_eng_app_df["Reviews"] = free_eng_app_df["Reviews"].astype(int)

C:\Users\Aksystems\AppData\Local\Temp\ipykernel_6836\290931285.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  free_eng_app_df["Reviews"] = free_eng_app_df["Reviews"].astype(int)

In [34]:
free_eng_app_df["Reviews"].min()

0

In [35]:
free_eng_app_df["Reviews"].max()

78158306

In [36]:
free_eng_app_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9998 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9998 non-null   object
 1   Category        9998 non-null   object
 2   Rating          8691 non-null   float64
 3   Reviews         9998 non-null   int32
 4   Size            9998 non-null   object
 5   Installs        9998 non-null   int32
 6   Type            9998 non-null   object
 7   Price           9998 non-null   object
 8   Content Rating  9998 non-null   object
 9   Genres          9998 non-null   object
 10  Last Updated    9998 non-null   object
 11  Current Ver     9992 non-null   object
 12  Android Ver     9997 non-null   object
dtypes: float64(1), int32(2), object(10)
memory usage: 1015.4+ KB

## sort data in descending order so we have the apps with max reviwews on top

In [37]:
free_eng_app_df.sort_values(by="Reviews", ascending = False)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2544,Facebook,SOCIAL,4.1,78158306,Varies with device,1000000000,Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
3943,Facebook,SOCIAL,4.1,78128208,Varies with device,1000000000,Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
336,WhatsApp Messenger,COMMUNICATION,4.4,69119316,Varies with device,1000000000,Free,0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
381,WhatsApp Messenger,COMMUNICATION,4.4,69119316,Varies with device,1000000000,Free,0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
3904,WhatsApp Messenger,COMMUNICATION,4.4,69109672,Varies with device,1000000000,Free,0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
...,...,...,...,...,...,...,...,...,...,...,...,...,...
652,PlusOne,DATING,NaN,0,10M,1,Free,0,Mature 17+,Dating,"July 17, 2018",1.1.1,4.2 and up
7447,CJ IT ApS,BUSINESS,NaN,0,18M,10,Free,0,Everyone,Business,"July 2, 2015",1.31.62.109,4.0 and up
10187,All AJK Board Matric Fa Fsc Results,FAMILY,NaN,0,2.6M,10,Free,0,Everyone,Education,"July 22, 2018",1,4.0 and up
649,Healthy Relationships Guide,DATING,NaN,0,8.2M,1,Free,0,Everyone,Dating,"July 31, 2018",2,4.0.3 and up
7168,Best Design CD Ideas,LIFESTYLE,NaN,0,13M,10,Free,0,Everyone,Lifestyle,"April 18, 2018",1.0.0,4.0.3 and up

In [38]:
# saving it in df
sorted_df = free_eng_app_df.sort_values(by="Reviews", ascending = False)

In [39]:
#drop duplicates
sorted_df.drop_duplicates(subset= "App" , keep = "first")    #last & false

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2544,Facebook,SOCIAL,4.1,78158306,Varies with device,1000000000,Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
336,WhatsApp Messenger,COMMUNICATION,4.4,69119316,Varies with device,1000000000,Free,0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
2604,Instagram,SOCIAL,4.5,66577446,Varies with device,1000000000,Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
382,Messenger – Text and Video Chat for Free,COMMUNICATION,4.0,56646578,Varies with device,1000000000,Free,0,Everyone,Communication,"August 1, 2018",Varies with device,Varies with device
1879,Clash of Clans,GAME,4.6,44893888,98M,100000000,Free,0,Everyone 10+,Strategy,"July 15, 2018",10.322.16,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
652,PlusOne,DATING,NaN,0,10M,1,Free,0,Mature 17+,Dating,"July 17, 2018",1.1.1,4.2 and up
7447,CJ IT ApS,BUSINESS,NaN,0,18M,10,Free,0,Everyone,Business,"July 2, 2015",1.31.62.109,4.0 and up
10187,All AJK Board Matric Fa Fsc Results,FAMILY,NaN,0,2.6M,10,Free,0,Everyone,Education,"July 22, 2018",1,4.0 and up
649,Healthy Relationships Guide,DATING,NaN,0,8.2M,1,Free,0,Everyone,Dating,"July 31, 2018",2,4.0.3 and up
7168,Best Design CD Ideas,LIFESTYLE,NaN,0,13M,10,Free,0,Everyone,Lifestyle,"April 18, 2018",1.0.0,4.0.3 and up

# saving clean & sorted df  in variables

In [40]:
clean_df = sorted_df.drop_duplicates(subset= "App" , keep = "first")

In [41]:
clean_df.shape

(8863, 13)

In [42]:
clean_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2544,Facebook,SOCIAL,4.1,78158306,Varies with device,1000000000,Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
336,WhatsApp Messenger,COMMUNICATION,4.4,69119316,Varies with device,1000000000,Free,0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
2604,Instagram,SOCIAL,4.5,66577446,Varies with device,1000000000,Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
382,Messenger – Text and Video Chat for Free,COMMUNICATION,4.0,56646578,Varies with device,1000000000,Free,0,Everyone,Communication,"August 1, 2018",Varies with device,Varies with device
1879,Clash of Clans,GAME,4.6,44893888,98M,100000000,Free,0,Everyone 10+,Strategy,"July 15, 2018",10.322.16,4.1 and up

## reset index

In [44]:
clean_df.reset_index(drop = True, inplace = True)

In [45]:
clean_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Facebook,SOCIAL,4.1,78158306,Varies with device,1000000000,Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
1,WhatsApp Messenger,COMMUNICATION,4.4,69119316,Varies with device,1000000000,Free,0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
2,Instagram,SOCIAL,4.5,66577446,Varies with device,1000000000,Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
3,Messenger – Text and Video Chat for Free,COMMUNICATION,4.0,56646578,Varies with device,1000000000,Free,0,Everyone,Communication,"August 1, 2018",Varies with device,Varies with device
4,Clash of Clans,GAME,4.6,44893888,98M,100000000,Free,0,Everyone 10+,Strategy,"July 15, 2018",10.322.16,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8858,PlusOne,DATING,NaN,0,10M,1,Free,0,Mature 17+,Dating,"July 17, 2018",1.1.1,4.2 and up
8859,CJ IT ApS,BUSINESS,NaN,0,18M,10,Free,0,Everyone,Business,"July 2, 2015",1.31.62.109,4.0 and up
8860,All AJK Board Matric Fa Fsc Results,FAMILY,NaN,0,2.6M,10,Free,0,Everyone,Education,"July 22, 2018",1,4.0 and up
8861,Healthy Relationships Guide,DATING,NaN,0,8.2M,1,Free,0,Everyone,Dating,"July 31, 2018",2,4.0.3 and up
8862,Best Design CD Ideas,LIFESTYLE,NaN,0,13M,10,Free,0,Everyone,Lifestyle,"April 18, 2018",1.0.0,4.0.3 and up

## groupby category to find out bets category

In [48]:
clean_df.groupby("Category")

In [49]:
clean_df["Category"].value_counts()

Category
FAMILY                 1677
GAME                    861
TOOLS                   750
BUSINESS                407
LIFESTYLE               346
PRODUCTIVITY            345
FINANCE                 328
MEDICAL                 313
SPORTS                  301
PERSONALIZATION         294
COMMUNICATION           287
HEALTH_AND_FITNESS      273
PHOTOGRAPHY             261
NEWS_AND_MAGAZINES      248
SOCIAL                  236
TRAVEL_AND_LOCAL        207
SHOPPING                199
BOOKS_AND_REFERENCE     190
DATING                  165
VIDEO_PLAYERS           159
MAPS_AND_NAVIGATION     124
FOOD_AND_DRINK          110
EDUCATION               103
ENTERTAINMENT            84
LIBRARIES_AND_DEMO       83
AUTO_AND_VEHICLES        82
HOUSE_AND_HOME           73
WEATHER                  71
EVENTS                   63
PARENTING                58
ART_AND_DESIGN           57
COMICS                   55
BEAUTY                   53
Name: count, dtype: int64

In [51]:
# as family category has highest numbers of apps so extracting family apps
bol_family  = clean_df["Category"] == "FAMILY"

In [52]:
fam_df = clean_df[bol_family]

In [53]:
fam_df.reset_index(drop = True)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Minion Rush: Despicable Me Official Game,FAMILY,4.5,10216997,Varies with device,100000000,Free,0,Everyone 10+,Casual;Action & Adventure,"July 12, 2018",Varies with device,Varies with device
1,Hay Day,FAMILY,4.5,10053186,94M,100000000,Free,0,Everyone,Casual,"June 28, 2018",1_39_93,4.0.3 and up
2,Farm Heroes Saga,FAMILY,4.4,7615646,71M,100000000,Free,0,Everyone,Casual,"August 7, 2018",5.2.6,2.3 and up
3,Google Play Games,FAMILY,4.3,7168735,Varies with device,1000000000,Free,0,Teen,Entertainment,"July 16, 2018",Varies with device,Varies with device
4,Duolingo: Learn Languages Free,FAMILY,4.7,6297590,Varies with device,100000000,Free,0,Everyone,Education;Education,"August 6, 2018",Varies with device,Varies with device
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1672,D.N. College Meerut,FAMILY,NaN,0,19M,10,Free,0,Everyone,Education,"March 26, 2018",1.0.0,4.0 and up
1673,DN Driver,FAMILY,NaN,0,7.5M,5,Free,0,Everyone,Education,"June 9, 2018",1.0.2,4.1 and up
1674,AQ: First Contact,FAMILY,NaN,0,Varies with device,50000,Free,0,Everyone,Strategy,"July 26, 2018",Varies with device,Varies with device
1675,CJ Auto école,FAMILY,NaN,0,12M,50,Free,0,Everyone,Education,"June 24, 2014",1,2.2 and up
1676,All AJK Board Matric Fa Fsc Results,FAMILY,NaN,0,2.6M,10,Free,0,Everyone,Education,"July 22, 2018",1,4.0 and up

In [54]:
sorted_fam_df = fam_df.sort_values(by= "Installs" , ascending = False)

In [55]:
# clean sorted data of english free family category apps 
sorted_fam_df.head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
51,Google Play Games,FAMILY,4.3,7168735,Varies with device,1000000000,Free,0,Teen,Entertainment,"July 16, 2018",Varies with device,Varies with device
27,Minion Rush: Despicable Me Official Game,FAMILY,4.5,10216997,Varies with device,100000000,Free,0,Everyone 10+,Casual;Action & Adventure,"July 12, 2018",Varies with device,Varies with device
129,Talking Tom Cat 2,FAMILY,4.3,3213548,55M,100000000,Free,0,Everyone 10+,Entertainment,"July 25, 2018",5.3.5.16,4.1 and up
318,Tom Loves Angela,FAMILY,4.1,1111915,50M,100000000,Free,0,Everyone,Entertainment,"April 30, 2018",2.2.1.3,4.1 and up
309,Talking Tom & Ben News,FAMILY,4.4,1131937,41M,100000000,Free,0,Everyone,Entertainment,"April 30, 2018",2.4.0.7,4.1 and up
208,Talking Ginger,FAMILY,4.2,1752017,52M,100000000,Free,0,Everyone,Entertainment,"July 5, 2018",2.5.6.11,4.1 and up
203,Talking Tom Cat,FAMILY,4.3,1838090,Varies with device,100000000,Free,0,Everyone 10+,Casual,"July 27, 2018",Varies with device,4.1 and up
177,Bitmoji – Your Personal Emoji,FAMILY,4.6,2312084,Varies with device,100000000,Free,0,Teen,Entertainment,"July 25, 2018",Varies with device,4.3 and up
29,Hay Day,FAMILY,4.5,10053186,94M,100000000,Free,0,Everyone,Casual,"June 28, 2018",1_39_93,4.0.3 and up
146,Bubble Witch 2 Saga,FAMILY,4.3,2838064,Varies with device,100000000,Free,0,Everyone,Casual,"August 6, 2018",Varies with device,Varies with device

# analysis
## KEY POINTS:

* Category with the Most Number of Apps: The family category has the highest number of apps.

* Top Ten Apps in the Family Category: Among the family category apps, we identified the top ten based on the most reviews and downloads.

* Generating Reviews through Advertisements: It's observed that launching apps in the family category could potentially generate reviews through advertisement exposure.


# Summary
"""After analyzing the app landscape, it's evident that the family category stands out with the highest number of apps. Further investigation revealed the top ten apps within this category, selected for their impressive number of reviews and downloads. Notably, apps in the family category present a strategic opportunity for generating reviews through targeted advertisements. Understanding the nature of the ads we showcase or securing sponsorships can provide valuable insights. With this knowledge, we can tailor our approach to developing apps across different genres as per the demands of the market. This flexibility enables us to capitalize on emerging trends and audience preferences, thereby maximizing our impact and potential for success"""

In [56]:
clean_df.to_csv("clean data.csv", index = False)

In [57]:
fam_df.to_csv("family apps data.csv", index = False)

In [58]:
duplicate_bool = data_df.duplicated('App')

In [59]:
duplicate_bool

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Length: 10840, dtype: bool

In [60]:
duplicate_bool.sum()    # true values

1181

In [61]:
duplicate = data_df[duplicate_bool]

In [62]:
data_df[duplicate_bool]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,5000000,Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,Varies with device,10000000,Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,Varies with device,5000000,Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,10000000,Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,1000000,Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10715,FarmersOnly Dating,DATING,3.0,1145,1.4M,100000,Free,0,Mature 17+,Dating,"February 25, 2016",2.2,4.0 and up
10720,Firefox Focus: The privacy browser,COMMUNICATION,4.4,36981,4.0M,1000000,Free,0,Everyone,Communication,"July 6, 2018",5.2,5.0 and up
10730,FP Notebook,MEDICAL,4.5,410,60M,50000,Free,0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up
10753,Slickdeals: Coupons & Shopping,SHOPPING,4.5,33599,12M,1000000,Free,0,Everyone,Shopping,"July 30, 2018",3.9,4.4 and up
10768,AAFP,MEDICAL,3.8,63,24M,10000,Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

----------------------xxxxxxx----------------Finish--------------------xxxxxxxxxxxxxxxx--------------------

# rough work

In [ ]:
free_eng_app_df.reset_index(drop = True , inplace = True)

In [ ]:
free_eng_app_df = clean_df

In [ ]:
unique_apps = free_eng_app_df["App"].unique()

In [ ]:
unique_apps

In [ ]:
unique_apps = data_df["App"].value_counts()

In [ ]:
unique_apps

In [ ]:
app_count = pd.Series[unique_apps[count] , index["App"]]

In [ ]:
duplicate_apps = free_eng_app_df.duplicated(subset=['App'])

In [ ]:

duplicate_apps

In [ ]:
duplicate_apps.sum()

In [ ]:
duplicate_app_df = free_eng_app_df[duplicate_apps]

In [ ]:
duplicate_app_df

In [ ]:
grouped_apps = free_eng_app_df.groupby("App")

In [ ]:
grouped_apps

In [ ]:
data_df["Installs"]

In [ ]:
pip install snakecase

In [ ]:
from snakecase import snakecase

In [ ]:
snake_case_chars = []
# Define a list to store the characters of the snake_case string
def to_snake_case(input_string):
    # Convert the input string to lowercase
    input_string = input_string.lower()

    # Iterate through each character of the input string
    for i, char in input_string:
        # If the current character is uppercase and not the first character
        if char.isupper() and i != 0:
            # Add an underscore before adding the lowercase version of the character
            schar.append('_')
        # Append the lowercase version of the character to the list
        schar_chars.append(char)

    # Join the characters to form the snake_case string
    snake_case_string = ''.join(snake_case_chars)
    return snake_case_string

In [ ]:
# Example usage:
input_string = "RegistrationOfYear"
snake_case_output = to_snake_case(input_string)
print(snake_case_output)  # Output: this_is_a_sample_string_with_punctuation

In [ ]:
to_snake_case("RegistrationOfYear")